# Generated by Django 4.1.5 on 2023-01-06 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("discounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountcard",
            name="card_number",
            field=models.BigIntegerField(unique=True,
                                         verbose_name="Numer Karty"),
        ),
        migrations.AlterField(
            model_name="discountcard",
            name="phone_number",
            field=models.BigIntegerField(unique=True,
                                         verbose_name="Numer telefonu"),
        ),
        migrations.AlterField(
            model_name="discountcoupon",
            name="start_validity_period",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Początek obowiązywania"
            ),
        ),
    ]
